package ca.weblite.notificationdemo;

import com.codename1.notifications.LocalNotification;
import com.codename1.notifications.LocalNotificationCallback;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class NotificationDemo extends Lifecycle implements LocalNotificationCallback {

    private static final String NOTIFICATION_ID = "test-notification";
    @Override
    public void runApp() {
        Form hi = new Form("Hi World", BoxLayout.y());
        Button sendForegroundNotification = new Button("Send Foreground Notification");
        hi.add(sendForegroundNotification);
        sendForegroundNotification.addActionListener(e -> sendForegroundNotification());
        Button sendBackgroundNotification = new Button("Send Background Notification");
        hi.add(sendBackgroundNotification);
        sendBackgroundNotification.addActionListener(e -> sendBackgroundNotification());

        hi.show();
    }

    private void sendForegroundNotification() {
        LocalNotification n = new LocalNotification();
        n.setForeground(true);
        n.setAlertBody("This is a local notification");
        n.setAlertTitle("Locaal Notification");
        n.setId(NOTIFICATION_ID);
        Log.p("Scheduling local notification " + n);
        Display.getInstance().scheduleLocalNotification(
                n,
                System.currentTimeMillis() + 5 * 1000,
                LocalNotification.REPEAT_NONE
        );

        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

    private void sendBackgroundNotification() {
        LocalNotification n = new LocalNotification();
        n.setForeground(false);
        n.setAlertBody("This is a local notification");
        n.setAlertTitle("Locaal Notification");
        n.setId(NOTIFICATION_ID);
        Log.p("Scheduling local notification " + n);
        Display.getInstance().scheduleLocalNotification(
                n,
                System.currentTimeMillis() + 5 * 1000,
                LocalNotification.REPEAT_NONE
        );

        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

    @Override
    public void localNotificationReceived(String s) {
        Log.p("Received local notification "+s);
        if (!Display.getInstance().isMinimized()) {
            Dialog.show("Notification", s, "OK", null);
        }
    }
}
